/** LINK-01 canonical deep-link mapping (contracts). */
export {
  CANONICAL_DEEP_LINK_MAPPING,
  DEEP_LINK_CONSUMERS,
  DEEP_LINK_ENTRIES,
  DEEP_LINK_EXTRA_OBJECT_CLASSES,
  DEEP_LINK_OBJECT_CLASSES,
  DEEP_LINK_PRODUCERS,
  DEEP_LINK_STAGES,
  DEEP_LINK_STAGE_TO_PANEL,
  canonicalDeepLinkRedirectHref,
  deepLinkConsumerFor,
  destinationPreservesIdentity,
  formatCanonicalDeepLinkHref,
  parseDeepLinkEntry,
  parseDeepLinkStage,
  resolveCanonicalDeepLink,
  serializeCanonicalDeepLink,
  type CanonicalDeepLinkDestination,
  type CanonicalDeepLinkIntent,
  type CanonicalDeepLinkMappingRow,
  type DeepLinkConsumer,
  type DeepLinkEntry,
  type DeepLinkExtraObjectClass,
  type DeepLinkMappedObjectClass,
  type DeepLinkObjectClass,
  type DeepLinkProducer,
  type DeepLinkStage,
} from '../../../packages/contracts/src/canonical-deep-link.ts';
