import {
  common_table_op_contains,
  common_table_op_greater_than,
  common_table_op_greater_than_or_equal,
  common_table_op_has_any_of,
  common_table_op_has_none_of,
  common_table_op_is,
  common_table_op_is_after,
  common_table_op_is_before,
  common_table_op_is_between,
  common_table_op_is_empty,
  common_table_op_is_not,
  common_table_op_is_not_empty,
  common_table_op_is_on_or_after,
  common_table_op_is_on_or_before,
  common_table_op_is_relative_to_today,
  common_table_op_less_than,
  common_table_op_less_than_or_equal,
  common_table_op_not_contains,
  common_table_sort_asc,
  common_table_sort_desc,
} from "@/locale/paraglide/messages";
export type DataTableConfig = typeof dataTableConfig;
export const dataTableConfig = {
    textOperators: [
        { label: common_table_op_contains(), value: "iLike" as const },
        { label: common_table_op_not_contains(), value: "notILike" as const },
        { label: common_table_op_is(), value: "eq" as const },
        { label: common_table_op_is_not(), value: "ne" as const },
        { label: common_table_op_is_empty(), value: "isEmpty" as const },
        { label: common_table_op_is_not_empty(), value: "isNotEmpty" as const },
    ],
    numericOperators: [
        { label: common_table_op_is(), value: "eq" as const },
        { label: common_table_op_is_not(), value: "ne" as const },
        { label: common_table_op_less_than(), value: "lt" as const },
        { label: common_table_op_less_than_or_equal(), value: "lte" as const },
        { label: common_table_op_greater_than(), value: "gt" as const },
        { label: common_table_op_greater_than_or_equal(), value: "gte" as const },
        { label: common_table_op_is_between(), value: "isBetween" as const },
        { label: common_table_op_is_empty(), value: "isEmpty" as const },
        { label: common_table_op_is_not_empty(), value: "isNotEmpty" as const },
    ],
    dateOperators: [
        { label: common_table_op_is(), value: "eq" as const },
        { label: common_table_op_is_not(), value: "ne" as const },
        { label: common_table_op_is_before(), value: "lt" as const },
        { label: common_table_op_is_after(), value: "gt" as const },
        { label: common_table_op_is_on_or_before(), value: "lte" as const },
        { label: common_table_op_is_on_or_after(), value: "gte" as const },
        { label: common_table_op_is_between(), value: "isBetween" as const },
        { label: common_table_op_is_relative_to_today(), value: "isRelativeToToday" as const },
        { label: common_table_op_is_empty(), value: "isEmpty" as const },
        { label: common_table_op_is_not_empty(), value: "isNotEmpty" as const },
    ],
    selectOperators: [
        { label: common_table_op_is(), value: "eq" as const },
        { label: common_table_op_is_not(), value: "ne" as const },
        { label: common_table_op_is_empty(), value: "isEmpty" as const },
        { label: common_table_op_is_not_empty(), value: "isNotEmpty" as const },
    ],
    multiSelectOperators: [
        { label: common_table_op_has_any_of(), value: "inArray" as const },
        { label: common_table_op_has_none_of(), value: "notInArray" as const },
        { label: common_table_op_is_empty(), value: "isEmpty" as const },
        { label: common_table_op_is_not_empty(), value: "isNotEmpty" as const },
    ],
    booleanOperators: [
        { label: common_table_op_is(), value: "eq" as const },
        { label: common_table_op_is_not(), value: "ne" as const },
    ],
    sortOrders: [
        { label: common_table_sort_asc(), value: "asc" as const },
        { label: common_table_sort_desc(), value: "desc" as const },
    ],
    filterVariants: [
        "text",
        "number",
        "range",
        "date",
        "dateRange",
        "boolean",
        "select",
        "multiSelect",
    ] as const,
    operators: [
        "iLike",
        "notILike",
        "eq",
        "ne",
        "inArray",
        "notInArray",
        "isEmpty",
        "isNotEmpty",
        "lt",
        "lte",
        "gt",
        "gte",
        "isBetween",
        "isRelativeToToday",
    ] as const,
    joinOperators: ["and", "or"] as const,
};
