/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PwaProofRouteImport } from './routes/pwa-proof'
import { Route as PrototypeMarketingHomeRouteImport } from './routes/prototype-marketing-home'
import { Route as ProStudioRouteImport } from './routes/pro-studio'
import { Route as ManifestDotjsonRouteImport } from './routes/manifest[.]json'
import { Route as HerouiSpikeRouteImport } from './routes/heroui-spike'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as HerouiSpikeIndexRouteImport } from './routes/heroui-spike/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SettingsSecurityRouteImport } from './routes/settings/security'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as SettingsPaymentRouteImport } from './routes/settings/payment'
import { Route as SettingsNotificationsRouteImport } from './routes/settings/notifications'
import { Route as SettingsModelsRouteImport } from './routes/settings/models'
import { Route as SettingsIntegrationsRouteImport } from './routes/settings/integrations'
import { Route as SettingsFilesRouteImport } from './routes/settings/files'
import { Route as SettingsCreditsRouteImport } from './routes/settings/credits'
import { Route as SettingsConnectionsRouteImport } from './routes/settings/connections'
import { Route as SettingsBillingRouteImport } from './routes/settings/billing'
import { Route as SettingsApikeysRouteImport } from './routes/settings/apikeys'
import { Route as SettingsAccountRouteImport } from './routes/settings/account'
import { Route as HerouiSpikeDashboardRouteImport } from './routes/heroui-spike/dashboard'
import { Route as HerouiSpikeChatRouteImport } from './routes/heroui-spike/chat'
import { Route as DashboardWorksRouteImport } from './routes/dashboard/works'
import { Route as DashboardTasksRouteImport } from './routes/dashboard/tasks'
import { Route as DashboardStoreRouteImport } from './routes/dashboard/store'
import { Route as DashboardSessionsRouteImport } from './routes/dashboard/sessions'
import { Route as DashboardSearchRouteImport } from './routes/dashboard/search'
import { Route as DashboardRecentRouteImport } from './routes/dashboard/recent'
import { Route as DashboardLeadsRouteImport } from './routes/dashboard/leads'
import { Route as DashboardJobsRouteImport } from './routes/dashboard/jobs'
import { Route as DashboardContentRouteImport } from './routes/dashboard/content'
import { Route as DashboardCatalogRouteImport } from './routes/dashboard/catalog'
import { Route as DashboardAssetsRouteImport } from './routes/dashboard/assets'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthErrorRouteImport } from './routes/auth/error'
import { Route as ApiPingRouteImport } from './routes/api/ping'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminTemplatesRouteImport } from './routes/admin/templates'
import { Route as AdminSupplyRouteImport } from './routes/admin/supply'
import { Route as AdminRedemptionsRouteImport } from './routes/admin/redemptions'
import { Route as AdminPlansRouteImport } from './routes/admin/plans'
import { Route as AdminP1RouteImport } from './routes/admin/p1'
import { Route as AdminModelsRouteImport } from './routes/admin/models'
import { Route as AdminIntegrationsRouteImport } from './routes/admin/integrations'
import { Route as AdminCloudflareRouteImport } from './routes/admin/cloudflare'
import { Route as AdminCapabilitiesRouteImport } from './routes/admin/capabilities'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as testsTestErrorRouteImport } from './routes/(tests)/test-error'
import { Route as testsTest404RouteImport } from './routes/(tests)/test-404'
import { Route as pagesPricingRouteImport } from './routes/(pages)/pricing'
import { Route as pagesContactRouteImport } from './routes/(pages)/contact'
import { Route as legalsTermsRouteImport } from './routes/(legals)/terms'
import { Route as legalsPrivacyRouteImport } from './routes/(legals)/privacy'
import { Route as legalsCookieRouteImport } from './routes/(legals)/cookie'
import { Route as DashboardWorksWorkIdRouteImport } from './routes/dashboard/works_/$workId'
import { Route as DashboardToolsToolEntryIdRouteImport } from './routes/dashboard/tools_/$toolEntryId'
import { Route as DashboardTasksTaskIdRouteImport } from './routes/dashboard/tasks_/$taskId'
import { Route as DashboardSessionsSessionIdRouteImport } from './routes/dashboard/sessions_/$sessionId'
import { Route as DashboardResultsWorkIdRouteImport } from './routes/dashboard/results_/$workId'
import { Route as DashboardLeadsLeadIdRouteImport } from './routes/dashboard/leads_/$leadId'
import { Route as DashboardJobsJobIdRouteImport } from './routes/dashboard/jobs_/$jobId'
import { Route as DashboardHandoffTokenRouteImport } from './routes/dashboard/handoff/$token'
import { Route as DashboardContentContentIdRouteImport } from './routes/dashboard/content_/$contentId'
import { Route as DashboardAssetsAssetIdRouteImport } from './routes/dashboard/assets_/$assetId'
import { Route as ApiWebhooksStripeRouteImport } from './routes/api/webhooks/stripe'
import { Route as ApiWebhooksCreemRouteImport } from './routes/api/webhooks/creem'
import { Route as ApiStorageUploadRouteImport } from './routes/api/storage/upload'
import { Route as ApiStorageFileRouteImport } from './routes/api/storage/file'
import { Route as ApiProStudioLaunchRouteImport } from './routes/api/pro-studio/launch'
import { Route as ApiProStudioEntryRouteImport } from './routes/api/pro-studio/entry'
import { Route as ApiProStudioCheckoutRouteImport } from './routes/api/pro-studio/checkout'
import { Route as ApiE2eUsersRouteImport } from './routes/api/e2e/users'
import { Route as ApiE2eProStudioPaymentRouteImport } from './routes/api/e2e/pro-studio-payment'
import { Route as ApiCoreDiagnosticsRouteImport } from './routes/api/core/diagnostics'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCoreProductStateRouteImport } from './routes/api/core/product/state'
import { Route as ApiCoreProductCommandsRouteImport } from './routes/api/core/product/commands'
import { Route as ApiCoreP1QueryRouteImport } from './routes/api/core/p1/query'
import { Route as ApiCoreP1PendingActionsRouteImport } from './routes/api/core/p1/pending-actions'
import { Route as ApiCoreP1CommandsRouteImport } from './routes/api/core/p1/commands'
import { Route as ApiCoreP1AssetsRouteImport } from './routes/api/core/p1/assets'
import { Route as AdminSupplyViewsViewIdRouteImport } from './routes/admin/supply.views.$viewId'
import { Route as AdminSupplyTasksTaskIdRouteImport } from './routes/admin/supply.tasks.$taskId'
import { Route as ApiCoreP1HarnessTasksRouteImport } from './routes/api/core/p1/harness/tasks'
import { Route as ApiCoreP1HarnessRecommendationRouteImport } from './routes/api/core/p1/harness/recommendation'
import { Route as ApiCoreP1CopyStreamRouteImport } from './routes/api/core/p1/copy/stream'
import { Route as ApiCoreP1ComposerSubmissionsRouteImport } from './routes/api/core/p1/composer/submissions'
import { Route as ApiCoreP1AssistantStreamRouteImport } from './routes/api/core/p1/assistant/stream'
import { Route as ApiCoreDiagnosticsIdResumeRouteImport } from './routes/api/core/diagnostics/$id/resume'
import { Route as ApiCoreDiagnosticsIdEventsRouteImport } from './routes/api/core/diagnostics/$id/events'
import { Route as ApiCoreP1WorkflowsWorkflowIdEventsRouteImport } from './routes/api/core/p1/workflows/$workflowId/events'
import { Route as ApiCoreP1HarnessTasksTaskIdProductMetricsRouteImport } from './routes/api/core/p1/harness/tasks/$taskId/product-metrics'
import { Route as ApiCoreP1HarnessTasksTaskIdDecisionRouteImport } from './routes/api/core/p1/harness/tasks/$taskId/decision'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PwaProofRoute = PwaProofRouteImport.update({
  id: '/pwa-proof',
  path: '/pwa-proof',
  getParentRoute: () => rootRouteImport,
} as any)
const PrototypeMarketingHomeRoute = PrototypeMarketingHomeRouteImport.update({
  id: '/prototype-marketing-home',
  path: '/prototype-marketing-home',
  getParentRoute: () => rootRouteImport,
} as any)
const ProStudioRoute = ProStudioRouteImport.update({
  id: '/pro-studio',
  path: '/pro-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestDotjsonRoute = ManifestDotjsonRouteImport.update({
  id: '/manifest.json',
  path: '/manifest.json',
  getParentRoute: () => rootRouteImport,
} as any)
const HerouiSpikeRoute = HerouiSpikeRouteImport.update({
  id: '/heroui-spike',
  path: '/heroui-spike',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const HerouiSpikeIndexRoute = HerouiSpikeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HerouiSpikeRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SettingsSecurityRoute = SettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPaymentRoute = SettingsPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsModelsRoute = SettingsModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsIntegrationsRoute = SettingsIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsFilesRoute = SettingsFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsCreditsRoute = SettingsCreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsConnectionsRoute = SettingsConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsBillingRoute = SettingsBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsApikeysRoute = SettingsApikeysRouteImport.update({
  id: '/apikeys',
  path: '/apikeys',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAccountRoute = SettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => SettingsRoute,
} as any)
const HerouiSpikeDashboardRoute = HerouiSpikeDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => HerouiSpikeRoute,
} as any)
const HerouiSpikeChatRoute = HerouiSpikeChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => HerouiSpikeRoute,
} as any)
const DashboardWorksRoute = DashboardWorksRouteImport.update({
  id: '/works',
  path: '/works',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTasksRoute = DashboardTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStoreRoute = DashboardStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSessionsRoute = DashboardSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSearchRoute = DashboardSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRecentRoute = DashboardRecentRouteImport.update({
  id: '/recent',
  path: '/recent',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLeadsRoute = DashboardLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardJobsRoute = DashboardJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardContentRoute = DashboardContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCatalogRoute = DashboardCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAssetsRoute = DashboardAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => AuthRoute,
} as any)
const ApiPingRoute = ApiPingRouteImport.update({
  id: '/api/ping',
  path: '/api/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTemplatesRoute = AdminTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupplyRoute = AdminSupplyRouteImport.update({
  id: '/supply',
  path: '/supply',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRedemptionsRoute = AdminRedemptionsRouteImport.update({
  id: '/redemptions',
  path: '/redemptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlansRoute = AdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AdminRoute,
} as any)
const AdminP1Route = AdminP1RouteImport.update({
  id: '/p1',
  path: '/p1',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModelsRoute = AdminModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIntegrationsRoute = AdminIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCloudflareRoute = AdminCloudflareRouteImport.update({
  id: '/cloudflare',
  path: '/cloudflare',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCapabilitiesRoute = AdminCapabilitiesRouteImport.update({
  id: '/capabilities',
  path: '/capabilities',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const testsTestErrorRoute = testsTestErrorRouteImport.update({
  id: '/(tests)/test-error',
  path: '/test-error',
  getParentRoute: () => rootRouteImport,
} as any)
const testsTest404Route = testsTest404RouteImport.update({
  id: '/(tests)/test-404',
  path: '/test-404',
  getParentRoute: () => rootRouteImport,
} as any)
const pagesPricingRoute = pagesPricingRouteImport.update({
  id: '/(pages)/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const pagesContactRoute = pagesContactRouteImport.update({
  id: '/(pages)/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const legalsTermsRoute = legalsTermsRouteImport.update({
  id: '/(legals)/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const legalsPrivacyRoute = legalsPrivacyRouteImport.update({
  id: '/(legals)/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const legalsCookieRoute = legalsCookieRouteImport.update({
  id: '/(legals)/cookie',
  path: '/cookie',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWorksWorkIdRoute = DashboardWorksWorkIdRouteImport.update({
  id: '/works_/$workId',
  path: '/works/$workId',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardToolsToolEntryIdRoute =
  DashboardToolsToolEntryIdRouteImport.update({
    id: '/tools_/$toolEntryId',
    path: '/tools/$toolEntryId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardTasksTaskIdRoute = DashboardTasksTaskIdRouteImport.update({
  id: '/tasks_/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSessionsSessionIdRoute =
  DashboardSessionsSessionIdRouteImport.update({
    id: '/sessions_/$sessionId',
    path: '/sessions/$sessionId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardResultsWorkIdRoute = DashboardResultsWorkIdRouteImport.update({
  id: '/results_/$workId',
  path: '/results/$workId',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLeadsLeadIdRoute = DashboardLeadsLeadIdRouteImport.update({
  id: '/leads_/$leadId',
  path: '/leads/$leadId',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardJobsJobIdRoute = DashboardJobsJobIdRouteImport.update({
  id: '/jobs_/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHandoffTokenRoute = DashboardHandoffTokenRouteImport.update({
  id: '/handoff/$token',
  path: '/handoff/$token',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardContentContentIdRoute =
  DashboardContentContentIdRouteImport.update({
    id: '/content_/$contentId',
    path: '/content/$contentId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAssetsAssetIdRoute = DashboardAssetsAssetIdRouteImport.update({
  id: '/assets_/$assetId',
  path: '/assets/$assetId',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiWebhooksStripeRoute = ApiWebhooksStripeRouteImport.update({
  id: '/api/webhooks/stripe',
  path: '/api/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksCreemRoute = ApiWebhooksCreemRouteImport.update({
  id: '/api/webhooks/creem',
  path: '/api/webhooks/creem',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageUploadRoute = ApiStorageUploadRouteImport.update({
  id: '/api/storage/upload',
  path: '/api/storage/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageFileRoute = ApiStorageFileRouteImport.update({
  id: '/api/storage/file',
  path: '/api/storage/file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProStudioLaunchRoute = ApiProStudioLaunchRouteImport.update({
  id: '/api/pro-studio/launch',
  path: '/api/pro-studio/launch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProStudioEntryRoute = ApiProStudioEntryRouteImport.update({
  id: '/api/pro-studio/entry',
  path: '/api/pro-studio/entry',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProStudioCheckoutRoute = ApiProStudioCheckoutRouteImport.update({
  id: '/api/pro-studio/checkout',
  path: '/api/pro-studio/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiE2eUsersRoute = ApiE2eUsersRouteImport.update({
  id: '/api/e2e/users',
  path: '/api/e2e/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiE2eProStudioPaymentRoute = ApiE2eProStudioPaymentRouteImport.update({
  id: '/api/e2e/pro-studio-payment',
  path: '/api/e2e/pro-studio-payment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoreDiagnosticsRoute = ApiCoreDiagnosticsRouteImport.update({
  id: '/api/core/diagnostics',
  path: '/api/core/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoreProductStateRoute = ApiCoreProductStateRouteImport.update({
  id: '/api/core/product/state',
  path: '/api/core/product/state',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoreProductCommandsRoute = ApiCoreProductCommandsRouteImport.update({
  id: '/api/core/product/commands',
  path: '/api/core/product/commands',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoreP1QueryRoute = ApiCoreP1QueryRouteImport.update({
  id: '/api/core/p1/query',
  path: '/api/core/p1/query',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoreP1PendingActionsRoute = ApiCoreP1PendingActionsRouteImport.update({
  id: '/api/core/p1/pending-actions',
  path: '/api/core/p1/pending-actions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoreP1CommandsRoute = ApiCoreP1CommandsRouteImport.update({
  id: '/api/core/p1/commands',
  path: '/api/core/p1/commands',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoreP1AssetsRoute = ApiCoreP1AssetsRouteImport.update({
  id: '/api/core/p1/assets',
  path: '/api/core/p1/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSupplyViewsViewIdRoute = AdminSupplyViewsViewIdRouteImport.update({
  id: '/views/$viewId',
  path: '/views/$viewId',
  getParentRoute: () => AdminSupplyRoute,
} as any)
const AdminSupplyTasksTaskIdRoute = AdminSupplyTasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => AdminSupplyRoute,
} as any)
const ApiCoreP1HarnessTasksRoute = ApiCoreP1HarnessTasksRouteImport.update({
  id: '/api/core/p1/harness/tasks',
  path: '/api/core/p1/harness/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoreP1HarnessRecommendationRoute =
  ApiCoreP1HarnessRecommendationRouteImport.update({
    id: '/api/core/p1/harness/recommendation',
    path: '/api/core/p1/harness/recommendation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCoreP1CopyStreamRoute = ApiCoreP1CopyStreamRouteImport.update({
  id: '/api/core/p1/copy/stream',
  path: '/api/core/p1/copy/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoreP1ComposerSubmissionsRoute =
  ApiCoreP1ComposerSubmissionsRouteImport.update({
    id: '/api/core/p1/composer/submissions',
    path: '/api/core/p1/composer/submissions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCoreP1AssistantStreamRoute =
  ApiCoreP1AssistantStreamRouteImport.update({
    id: '/api/core/p1/assistant/stream',
    path: '/api/core/p1/assistant/stream',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCoreDiagnosticsIdResumeRoute =
  ApiCoreDiagnosticsIdResumeRouteImport.update({
    id: '/$id/resume',
    path: '/$id/resume',
    getParentRoute: () => ApiCoreDiagnosticsRoute,
  } as any)
const ApiCoreDiagnosticsIdEventsRoute =
  ApiCoreDiagnosticsIdEventsRouteImport.update({
    id: '/$id/events',
    path: '/$id/events',
    getParentRoute: () => ApiCoreDiagnosticsRoute,
  } as any)
const ApiCoreP1WorkflowsWorkflowIdEventsRoute =
  ApiCoreP1WorkflowsWorkflowIdEventsRouteImport.update({
    id: '/api/core/p1/workflows/$workflowId/events',
    path: '/api/core/p1/workflows/$workflowId/events',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCoreP1HarnessTasksTaskIdProductMetricsRoute =
  ApiCoreP1HarnessTasksTaskIdProductMetricsRouteImport.update({
    id: '/$taskId/product-metrics',
    path: '/$taskId/product-metrics',
    getParentRoute: () => ApiCoreP1HarnessTasksRoute,
  } as any)
const ApiCoreP1HarnessTasksTaskIdDecisionRoute =
  ApiCoreP1HarnessTasksTaskIdDecisionRouteImport.update({
    id: '/$taskId/decision',
    path: '/$taskId/decision',
    getParentRoute: () => ApiCoreP1HarnessTasksRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/heroui-spike': typeof HerouiSpikeRouteWithChildren
  '/manifest.json': typeof ManifestDotjsonRoute
  '/pro-studio': typeof ProStudioRoute
  '/prototype-marketing-home': typeof PrototypeMarketingHomeRoute
  '/pwa-proof': typeof PwaProofRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/settings': typeof SettingsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/cookie': typeof legalsCookieRoute
  '/privacy': typeof legalsPrivacyRoute
  '/terms': typeof legalsTermsRoute
  '/contact': typeof pagesContactRoute
  '/pricing': typeof pagesPricingRoute
  '/test-404': typeof testsTest404Route
  '/test-error': typeof testsTestErrorRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/capabilities': typeof AdminCapabilitiesRoute
  '/admin/cloudflare': typeof AdminCloudflareRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/models': typeof AdminModelsRoute
  '/admin/p1': typeof AdminP1Route
  '/admin/plans': typeof AdminPlansRoute
  '/admin/redemptions': typeof AdminRedemptionsRoute
  '/admin/supply': typeof AdminSupplyRouteWithChildren
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/ping': typeof ApiPingRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/dashboard/assets': typeof DashboardAssetsRoute
  '/dashboard/catalog': typeof DashboardCatalogRoute
  '/dashboard/content': typeof DashboardContentRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/recent': typeof DashboardRecentRoute
  '/dashboard/search': typeof DashboardSearchRoute
  '/dashboard/sessions': typeof DashboardSessionsRoute
  '/dashboard/store': typeof DashboardStoreRoute
  '/dashboard/tasks': typeof DashboardTasksRoute
  '/dashboard/works': typeof DashboardWorksRoute
  '/heroui-spike/chat': typeof HerouiSpikeChatRoute
  '/heroui-spike/dashboard': typeof HerouiSpikeDashboardRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/apikeys': typeof SettingsApikeysRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/credits': typeof SettingsCreditsRoute
  '/settings/files': typeof SettingsFilesRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/models': typeof SettingsModelsRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/payment': typeof SettingsPaymentRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/heroui-spike/': typeof HerouiSpikeIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/core/diagnostics': typeof ApiCoreDiagnosticsRouteWithChildren
  '/api/e2e/pro-studio-payment': typeof ApiE2eProStudioPaymentRoute
  '/api/e2e/users': typeof ApiE2eUsersRoute
  '/api/pro-studio/checkout': typeof ApiProStudioCheckoutRoute
  '/api/pro-studio/entry': typeof ApiProStudioEntryRoute
  '/api/pro-studio/launch': typeof ApiProStudioLaunchRoute
  '/api/storage/file': typeof ApiStorageFileRoute
  '/api/storage/upload': typeof ApiStorageUploadRoute
  '/api/webhooks/creem': typeof ApiWebhooksCreemRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/dashboard/assets/$assetId': typeof DashboardAssetsAssetIdRoute
  '/dashboard/content/$contentId': typeof DashboardContentContentIdRoute
  '/dashboard/handoff/$token': typeof DashboardHandoffTokenRoute
  '/dashboard/jobs/$jobId': typeof DashboardJobsJobIdRoute
  '/dashboard/leads/$leadId': typeof DashboardLeadsLeadIdRoute
  '/dashboard/results/$workId': typeof DashboardResultsWorkIdRoute
  '/dashboard/sessions/$sessionId': typeof DashboardSessionsSessionIdRoute
  '/dashboard/tasks/$taskId': typeof DashboardTasksTaskIdRoute
  '/dashboard/tools/$toolEntryId': typeof DashboardToolsToolEntryIdRoute
  '/dashboard/works/$workId': typeof DashboardWorksWorkIdRoute
  '/admin/supply/tasks/$taskId': typeof AdminSupplyTasksTaskIdRoute
  '/admin/supply/views/$viewId': typeof AdminSupplyViewsViewIdRoute
  '/api/core/p1/assets': typeof ApiCoreP1AssetsRoute
  '/api/core/p1/commands': typeof ApiCoreP1CommandsRoute
  '/api/core/p1/pending-actions': typeof ApiCoreP1PendingActionsRoute
  '/api/core/p1/query': typeof ApiCoreP1QueryRoute
  '/api/core/product/commands': typeof ApiCoreProductCommandsRoute
  '/api/core/product/state': typeof ApiCoreProductStateRoute
  '/api/core/diagnostics/$id/events': typeof ApiCoreDiagnosticsIdEventsRoute
  '/api/core/diagnostics/$id/resume': typeof ApiCoreDiagnosticsIdResumeRoute
  '/api/core/p1/assistant/stream': typeof ApiCoreP1AssistantStreamRoute
  '/api/core/p1/composer/submissions': typeof ApiCoreP1ComposerSubmissionsRoute
  '/api/core/p1/copy/stream': typeof ApiCoreP1CopyStreamRoute
  '/api/core/p1/harness/recommendation': typeof ApiCoreP1HarnessRecommendationRoute
  '/api/core/p1/harness/tasks': typeof ApiCoreP1HarnessTasksRouteWithChildren
  '/api/core/p1/workflows/$workflowId/events': typeof ApiCoreP1WorkflowsWorkflowIdEventsRoute
  '/api/core/p1/harness/tasks/$taskId/decision': typeof ApiCoreP1HarnessTasksTaskIdDecisionRoute
  '/api/core/p1/harness/tasks/$taskId/product-metrics': typeof ApiCoreP1HarnessTasksTaskIdProductMetricsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/manifest.json': typeof ManifestDotjsonRoute
  '/pro-studio': typeof ProStudioRoute
  '/prototype-marketing-home': typeof PrototypeMarketingHomeRoute
  '/pwa-proof': typeof PwaProofRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/cookie': typeof legalsCookieRoute
  '/privacy': typeof legalsPrivacyRoute
  '/terms': typeof legalsTermsRoute
  '/contact': typeof pagesContactRoute
  '/pricing': typeof pagesPricingRoute
  '/test-404': typeof testsTest404Route
  '/test-error': typeof testsTestErrorRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/capabilities': typeof AdminCapabilitiesRoute
  '/admin/cloudflare': typeof AdminCloudflareRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/models': typeof AdminModelsRoute
  '/admin/p1': typeof AdminP1Route
  '/admin/plans': typeof AdminPlansRoute
  '/admin/redemptions': typeof AdminRedemptionsRoute
  '/admin/supply': typeof AdminSupplyRouteWithChildren
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/ping': typeof ApiPingRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/dashboard/assets': typeof DashboardAssetsRoute
  '/dashboard/catalog': typeof DashboardCatalogRoute
  '/dashboard/content': typeof DashboardContentRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/recent': typeof DashboardRecentRoute
  '/dashboard/search': typeof DashboardSearchRoute
  '/dashboard/sessions': typeof DashboardSessionsRoute
  '/dashboard/store': typeof DashboardStoreRoute
  '/dashboard/tasks': typeof DashboardTasksRoute
  '/dashboard/works': typeof DashboardWorksRoute
  '/heroui-spike/chat': typeof HerouiSpikeChatRoute
  '/heroui-spike/dashboard': typeof HerouiSpikeDashboardRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/apikeys': typeof SettingsApikeysRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/credits': typeof SettingsCreditsRoute
  '/settings/files': typeof SettingsFilesRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/models': typeof SettingsModelsRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/payment': typeof SettingsPaymentRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/heroui-spike': typeof HerouiSpikeIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/core/diagnostics': typeof ApiCoreDiagnosticsRouteWithChildren
  '/api/e2e/pro-studio-payment': typeof ApiE2eProStudioPaymentRoute
  '/api/e2e/users': typeof ApiE2eUsersRoute
  '/api/pro-studio/checkout': typeof ApiProStudioCheckoutRoute
  '/api/pro-studio/entry': typeof ApiProStudioEntryRoute
  '/api/pro-studio/launch': typeof ApiProStudioLaunchRoute
  '/api/storage/file': typeof ApiStorageFileRoute
  '/api/storage/upload': typeof ApiStorageUploadRoute
  '/api/webhooks/creem': typeof ApiWebhooksCreemRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/dashboard/assets/$assetId': typeof DashboardAssetsAssetIdRoute
  '/dashboard/content/$contentId': typeof DashboardContentContentIdRoute
  '/dashboard/handoff/$token': typeof DashboardHandoffTokenRoute
  '/dashboard/jobs/$jobId': typeof DashboardJobsJobIdRoute
  '/dashboard/leads/$leadId': typeof DashboardLeadsLeadIdRoute
  '/dashboard/results/$workId': typeof DashboardResultsWorkIdRoute
  '/dashboard/sessions/$sessionId': typeof DashboardSessionsSessionIdRoute
  '/dashboard/tasks/$taskId': typeof DashboardTasksTaskIdRoute
  '/dashboard/tools/$toolEntryId': typeof DashboardToolsToolEntryIdRoute
  '/dashboard/works/$workId': typeof DashboardWorksWorkIdRoute
  '/admin/supply/tasks/$taskId': typeof AdminSupplyTasksTaskIdRoute
  '/admin/supply/views/$viewId': typeof AdminSupplyViewsViewIdRoute
  '/api/core/p1/assets': typeof ApiCoreP1AssetsRoute
  '/api/core/p1/commands': typeof ApiCoreP1CommandsRoute
  '/api/core/p1/pending-actions': typeof ApiCoreP1PendingActionsRoute
  '/api/core/p1/query': typeof ApiCoreP1QueryRoute
  '/api/core/product/commands': typeof ApiCoreProductCommandsRoute
  '/api/core/product/state': typeof ApiCoreProductStateRoute
  '/api/core/diagnostics/$id/events': typeof ApiCoreDiagnosticsIdEventsRoute
  '/api/core/diagnostics/$id/resume': typeof ApiCoreDiagnosticsIdResumeRoute
  '/api/core/p1/assistant/stream': typeof ApiCoreP1AssistantStreamRoute
  '/api/core/p1/composer/submissions': typeof ApiCoreP1ComposerSubmissionsRoute
  '/api/core/p1/copy/stream': typeof ApiCoreP1CopyStreamRoute
  '/api/core/p1/harness/recommendation': typeof ApiCoreP1HarnessRecommendationRoute
  '/api/core/p1/harness/tasks': typeof ApiCoreP1HarnessTasksRouteWithChildren
  '/api/core/p1/workflows/$workflowId/events': typeof ApiCoreP1WorkflowsWorkflowIdEventsRoute
  '/api/core/p1/harness/tasks/$taskId/decision': typeof ApiCoreP1HarnessTasksTaskIdDecisionRoute
  '/api/core/p1/harness/tasks/$taskId/product-metrics': typeof ApiCoreP1HarnessTasksTaskIdProductMetricsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/heroui-spike': typeof HerouiSpikeRouteWithChildren
  '/manifest.json': typeof ManifestDotjsonRoute
  '/pro-studio': typeof ProStudioRoute
  '/prototype-marketing-home': typeof PrototypeMarketingHomeRoute
  '/pwa-proof': typeof PwaProofRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/settings': typeof SettingsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/(legals)/cookie': typeof legalsCookieRoute
  '/(legals)/privacy': typeof legalsPrivacyRoute
  '/(legals)/terms': typeof legalsTermsRoute
  '/(pages)/contact': typeof pagesContactRoute
  '/(pages)/pricing': typeof pagesPricingRoute
  '/(tests)/test-404': typeof testsTest404Route
  '/(tests)/test-error': typeof testsTestErrorRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/capabilities': typeof AdminCapabilitiesRoute
  '/admin/cloudflare': typeof AdminCloudflareRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/models': typeof AdminModelsRoute
  '/admin/p1': typeof AdminP1Route
  '/admin/plans': typeof AdminPlansRoute
  '/admin/redemptions': typeof AdminRedemptionsRoute
  '/admin/supply': typeof AdminSupplyRouteWithChildren
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/ping': typeof ApiPingRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/dashboard/assets': typeof DashboardAssetsRoute
  '/dashboard/catalog': typeof DashboardCatalogRoute
  '/dashboard/content': typeof DashboardContentRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/recent': typeof DashboardRecentRoute
  '/dashboard/search': typeof DashboardSearchRoute
  '/dashboard/sessions': typeof DashboardSessionsRoute
  '/dashboard/store': typeof DashboardStoreRoute
  '/dashboard/tasks': typeof DashboardTasksRoute
  '/dashboard/works': typeof DashboardWorksRoute
  '/heroui-spike/chat': typeof HerouiSpikeChatRoute
  '/heroui-spike/dashboard': typeof HerouiSpikeDashboardRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/apikeys': typeof SettingsApikeysRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/credits': typeof SettingsCreditsRoute
  '/settings/files': typeof SettingsFilesRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/models': typeof SettingsModelsRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/payment': typeof SettingsPaymentRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/heroui-spike/': typeof HerouiSpikeIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/core/diagnostics': typeof ApiCoreDiagnosticsRouteWithChildren
  '/api/e2e/pro-studio-payment': typeof ApiE2eProStudioPaymentRoute
  '/api/e2e/users': typeof ApiE2eUsersRoute
  '/api/pro-studio/checkout': typeof ApiProStudioCheckoutRoute
  '/api/pro-studio/entry': typeof ApiProStudioEntryRoute
  '/api/pro-studio/launch': typeof ApiProStudioLaunchRoute
  '/api/storage/file': typeof ApiStorageFileRoute
  '/api/storage/upload': typeof ApiStorageUploadRoute
  '/api/webhooks/creem': typeof ApiWebhooksCreemRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/dashboard/assets_/$assetId': typeof DashboardAssetsAssetIdRoute
  '/dashboard/content_/$contentId': typeof DashboardContentContentIdRoute
  '/dashboard/handoff/$token': typeof DashboardHandoffTokenRoute
  '/dashboard/jobs_/$jobId': typeof DashboardJobsJobIdRoute
  '/dashboard/leads_/$leadId': typeof DashboardLeadsLeadIdRoute
  '/dashboard/results_/$workId': typeof DashboardResultsWorkIdRoute
  '/dashboard/sessions_/$sessionId': typeof DashboardSessionsSessionIdRoute
  '/dashboard/tasks_/$taskId': typeof DashboardTasksTaskIdRoute
  '/dashboard/tools_/$toolEntryId': typeof DashboardToolsToolEntryIdRoute
  '/dashboard/works_/$workId': typeof DashboardWorksWorkIdRoute
  '/admin/supply/tasks/$taskId': typeof AdminSupplyTasksTaskIdRoute
  '/admin/supply/views/$viewId': typeof AdminSupplyViewsViewIdRoute
  '/api/core/p1/assets': typeof ApiCoreP1AssetsRoute
  '/api/core/p1/commands': typeof ApiCoreP1CommandsRoute
  '/api/core/p1/pending-actions': typeof ApiCoreP1PendingActionsRoute
  '/api/core/p1/query': typeof ApiCoreP1QueryRoute
  '/api/core/product/commands': typeof ApiCoreProductCommandsRoute
  '/api/core/product/state': typeof ApiCoreProductStateRoute
  '/api/core/diagnostics/$id/events': typeof ApiCoreDiagnosticsIdEventsRoute
  '/api/core/diagnostics/$id/resume': typeof ApiCoreDiagnosticsIdResumeRoute
  '/api/core/p1/assistant/stream': typeof ApiCoreP1AssistantStreamRoute
  '/api/core/p1/composer/submissions': typeof ApiCoreP1ComposerSubmissionsRoute
  '/api/core/p1/copy/stream': typeof ApiCoreP1CopyStreamRoute
  '/api/core/p1/harness/recommendation': typeof ApiCoreP1HarnessRecommendationRoute
  '/api/core/p1/harness/tasks': typeof ApiCoreP1HarnessTasksRouteWithChildren
  '/api/core/p1/workflows/$workflowId/events': typeof ApiCoreP1WorkflowsWorkflowIdEventsRoute
  '/api/core/p1/harness/tasks/$taskId/decision': typeof ApiCoreP1HarnessTasksTaskIdDecisionRoute
  '/api/core/p1/harness/tasks/$taskId/product-metrics': typeof ApiCoreP1HarnessTasksTaskIdProductMetricsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/heroui-spike'
    | '/manifest.json'
    | '/pro-studio'
    | '/prototype-marketing-home'
    | '/pwa-proof'
    | '/robots.txt'
    | '/settings'
    | '/sitemap.xml'
    | '/cookie'
    | '/privacy'
    | '/terms'
    | '/contact'
    | '/pricing'
    | '/test-404'
    | '/test-error'
    | '/admin/audit'
    | '/admin/capabilities'
    | '/admin/cloudflare'
    | '/admin/integrations'
    | '/admin/models'
    | '/admin/p1'
    | '/admin/plans'
    | '/admin/redemptions'
    | '/admin/supply'
    | '/admin/templates'
    | '/admin/users'
    | '/api/ping'
    | '/auth/error'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/dashboard/assets'
    | '/dashboard/catalog'
    | '/dashboard/content'
    | '/dashboard/jobs'
    | '/dashboard/leads'
    | '/dashboard/recent'
    | '/dashboard/search'
    | '/dashboard/sessions'
    | '/dashboard/store'
    | '/dashboard/tasks'
    | '/dashboard/works'
    | '/heroui-spike/chat'
    | '/heroui-spike/dashboard'
    | '/settings/account'
    | '/settings/apikeys'
    | '/settings/billing'
    | '/settings/connections'
    | '/settings/credits'
    | '/settings/files'
    | '/settings/integrations'
    | '/settings/models'
    | '/settings/notifications'
    | '/settings/payment'
    | '/settings/profile'
    | '/settings/security'
    | '/admin/'
    | '/dashboard/'
    | '/heroui-spike/'
    | '/settings/'
    | '/api/auth/$'
    | '/api/core/diagnostics'
    | '/api/e2e/pro-studio-payment'
    | '/api/e2e/users'
    | '/api/pro-studio/checkout'
    | '/api/pro-studio/entry'
    | '/api/pro-studio/launch'
    | '/api/storage/file'
    | '/api/storage/upload'
    | '/api/webhooks/creem'
    | '/api/webhooks/stripe'
    | '/dashboard/assets/$assetId'
    | '/dashboard/content/$contentId'
    | '/dashboard/handoff/$token'
    | '/dashboard/jobs/$jobId'
    | '/dashboard/leads/$leadId'
    | '/dashboard/results/$workId'
    | '/dashboard/sessions/$sessionId'
    | '/dashboard/tasks/$taskId'
    | '/dashboard/tools/$toolEntryId'
    | '/dashboard/works/$workId'
    | '/admin/supply/tasks/$taskId'
    | '/admin/supply/views/$viewId'
    | '/api/core/p1/assets'
    | '/api/core/p1/commands'
    | '/api/core/p1/pending-actions'
    | '/api/core/p1/query'
    | '/api/core/product/commands'
    | '/api/core/product/state'
    | '/api/core/diagnostics/$id/events'
    | '/api/core/diagnostics/$id/resume'
    | '/api/core/p1/assistant/stream'
    | '/api/core/p1/composer/submissions'
    | '/api/core/p1/copy/stream'
    | '/api/core/p1/harness/recommendation'
    | '/api/core/p1/harness/tasks'
    | '/api/core/p1/workflows/$workflowId/events'
    | '/api/core/p1/harness/tasks/$taskId/decision'
    | '/api/core/p1/harness/tasks/$taskId/product-metrics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/manifest.json'
    | '/pro-studio'
    | '/prototype-marketing-home'
    | '/pwa-proof'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/cookie'
    | '/privacy'
    | '/terms'
    | '/contact'
    | '/pricing'
    | '/test-404'
    | '/test-error'
    | '/admin/audit'
    | '/admin/capabilities'
    | '/admin/cloudflare'
    | '/admin/integrations'
    | '/admin/models'
    | '/admin/p1'
    | '/admin/plans'
    | '/admin/redemptions'
    | '/admin/supply'
    | '/admin/templates'
    | '/admin/users'
    | '/api/ping'
    | '/auth/error'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/dashboard/assets'
    | '/dashboard/catalog'
    | '/dashboard/content'
    | '/dashboard/jobs'
    | '/dashboard/leads'
    | '/dashboard/recent'
    | '/dashboard/search'
    | '/dashboard/sessions'
    | '/dashboard/store'
    | '/dashboard/tasks'
    | '/dashboard/works'
    | '/heroui-spike/chat'
    | '/heroui-spike/dashboard'
    | '/settings/account'
    | '/settings/apikeys'
    | '/settings/billing'
    | '/settings/connections'
    | '/settings/credits'
    | '/settings/files'
    | '/settings/integrations'
    | '/settings/models'
    | '/settings/notifications'
    | '/settings/payment'
    | '/settings/profile'
    | '/settings/security'
    | '/admin'
    | '/dashboard'
    | '/heroui-spike'
    | '/settings'
    | '/api/auth/$'
    | '/api/core/diagnostics'
    | '/api/e2e/pro-studio-payment'
    | '/api/e2e/users'
    | '/api/pro-studio/checkout'
    | '/api/pro-studio/entry'
    | '/api/pro-studio/launch'
    | '/api/storage/file'
    | '/api/storage/upload'
    | '/api/webhooks/creem'
    | '/api/webhooks/stripe'
    | '/dashboard/assets/$assetId'
    | '/dashboard/content/$contentId'
    | '/dashboard/handoff/$token'
    | '/dashboard/jobs/$jobId'
    | '/dashboard/leads/$leadId'
    | '/dashboard/results/$workId'
    | '/dashboard/sessions/$sessionId'
    | '/dashboard/tasks/$taskId'
    | '/dashboard/tools/$toolEntryId'
    | '/dashboard/works/$workId'
    | '/admin/supply/tasks/$taskId'
    | '/admin/supply/views/$viewId'
    | '/api/core/p1/assets'
    | '/api/core/p1/commands'
    | '/api/core/p1/pending-actions'
    | '/api/core/p1/query'
    | '/api/core/product/commands'
    | '/api/core/product/state'
    | '/api/core/diagnostics/$id/events'
    | '/api/core/diagnostics/$id/resume'
    | '/api/core/p1/assistant/stream'
    | '/api/core/p1/composer/submissions'
    | '/api/core/p1/copy/stream'
    | '/api/core/p1/harness/recommendation'
    | '/api/core/p1/harness/tasks'
    | '/api/core/p1/workflows/$workflowId/events'
    | '/api/core/p1/harness/tasks/$taskId/decision'
    | '/api/core/p1/harness/tasks/$taskId/product-metrics'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/heroui-spike'
    | '/manifest.json'
    | '/pro-studio'
    | '/prototype-marketing-home'
    | '/pwa-proof'
    | '/robots.txt'
    | '/settings'
    | '/sitemap.xml'
    | '/(legals)/cookie'
    | '/(legals)/privacy'
    | '/(legals)/terms'
    | '/(pages)/contact'
    | '/(pages)/pricing'
    | '/(tests)/test-404'
    | '/(tests)/test-error'
    | '/admin/audit'
    | '/admin/capabilities'
    | '/admin/cloudflare'
    | '/admin/integrations'
    | '/admin/models'
    | '/admin/p1'
    | '/admin/plans'
    | '/admin/redemptions'
    | '/admin/supply'
    | '/admin/templates'
    | '/admin/users'
    | '/api/ping'
    | '/auth/error'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/dashboard/assets'
    | '/dashboard/catalog'
    | '/dashboard/content'
    | '/dashboard/jobs'
    | '/dashboard/leads'
    | '/dashboard/recent'
    | '/dashboard/search'
    | '/dashboard/sessions'
    | '/dashboard/store'
    | '/dashboard/tasks'
    | '/dashboard/works'
    | '/heroui-spike/chat'
    | '/heroui-spike/dashboard'
    | '/settings/account'
    | '/settings/apikeys'
    | '/settings/billing'
    | '/settings/connections'
    | '/settings/credits'
    | '/settings/files'
    | '/settings/integrations'
    | '/settings/models'
    | '/settings/notifications'
    | '/settings/payment'
    | '/settings/profile'
    | '/settings/security'
    | '/admin/'
    | '/dashboard/'
    | '/heroui-spike/'
    | '/settings/'
    | '/api/auth/$'
    | '/api/core/diagnostics'
    | '/api/e2e/pro-studio-payment'
    | '/api/e2e/users'
    | '/api/pro-studio/checkout'
    | '/api/pro-studio/entry'
    | '/api/pro-studio/launch'
    | '/api/storage/file'
    | '/api/storage/upload'
    | '/api/webhooks/creem'
    | '/api/webhooks/stripe'
    | '/dashboard/assets_/$assetId'
    | '/dashboard/content_/$contentId'
    | '/dashboard/handoff/$token'
    | '/dashboard/jobs_/$jobId'
    | '/dashboard/leads_/$leadId'
    | '/dashboard/results_/$workId'
    | '/dashboard/sessions_/$sessionId'
    | '/dashboard/tasks_/$taskId'
    | '/dashboard/tools_/$toolEntryId'
    | '/dashboard/works_/$workId'
    | '/admin/supply/tasks/$taskId'
    | '/admin/supply/views/$viewId'
    | '/api/core/p1/assets'
    | '/api/core/p1/commands'
    | '/api/core/p1/pending-actions'
    | '/api/core/p1/query'
    | '/api/core/product/commands'
    | '/api/core/product/state'
    | '/api/core/diagnostics/$id/events'
    | '/api/core/diagnostics/$id/resume'
    | '/api/core/p1/assistant/stream'
    | '/api/core/p1/composer/submissions'
    | '/api/core/p1/copy/stream'
    | '/api/core/p1/harness/recommendation'
    | '/api/core/p1/harness/tasks'
    | '/api/core/p1/workflows/$workflowId/events'
    | '/api/core/p1/harness/tasks/$taskId/decision'
    | '/api/core/p1/harness/tasks/$taskId/product-metrics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  HerouiSpikeRoute: typeof HerouiSpikeRouteWithChildren
  ManifestDotjsonRoute: typeof ManifestDotjsonRoute
  ProStudioRoute: typeof ProStudioRoute
  PrototypeMarketingHomeRoute: typeof PrototypeMarketingHomeRoute
  PwaProofRoute: typeof PwaProofRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  legalsCookieRoute: typeof legalsCookieRoute
  legalsPrivacyRoute: typeof legalsPrivacyRoute
  legalsTermsRoute: typeof legalsTermsRoute
  pagesContactRoute: typeof pagesContactRoute
  pagesPricingRoute: typeof pagesPricingRoute
  testsTest404Route: typeof testsTest404Route
  testsTestErrorRoute: typeof testsTestErrorRoute
  ApiPingRoute: typeof ApiPingRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCoreDiagnosticsRoute: typeof ApiCoreDiagnosticsRouteWithChildren
  ApiE2eProStudioPaymentRoute: typeof ApiE2eProStudioPaymentRoute
  ApiE2eUsersRoute: typeof ApiE2eUsersRoute
  ApiProStudioCheckoutRoute: typeof ApiProStudioCheckoutRoute
  ApiProStudioEntryRoute: typeof ApiProStudioEntryRoute
  ApiProStudioLaunchRoute: typeof ApiProStudioLaunchRoute
  ApiStorageFileRoute: typeof ApiStorageFileRoute
  ApiStorageUploadRoute: typeof ApiStorageUploadRoute
  ApiWebhooksCreemRoute: typeof ApiWebhooksCreemRoute
  ApiWebhooksStripeRoute: typeof ApiWebhooksStripeRoute
  ApiCoreP1AssetsRoute: typeof ApiCoreP1AssetsRoute
  ApiCoreP1CommandsRoute: typeof ApiCoreP1CommandsRoute
  ApiCoreP1PendingActionsRoute: typeof ApiCoreP1PendingActionsRoute
  ApiCoreP1QueryRoute: typeof ApiCoreP1QueryRoute
  ApiCoreProductCommandsRoute: typeof ApiCoreProductCommandsRoute
  ApiCoreProductStateRoute: typeof ApiCoreProductStateRoute
  ApiCoreP1AssistantStreamRoute: typeof ApiCoreP1AssistantStreamRoute
  ApiCoreP1ComposerSubmissionsRoute: typeof ApiCoreP1ComposerSubmissionsRoute
  ApiCoreP1CopyStreamRoute: typeof ApiCoreP1CopyStreamRoute
  ApiCoreP1HarnessRecommendationRoute: typeof ApiCoreP1HarnessRecommendationRoute
  ApiCoreP1HarnessTasksRoute: typeof ApiCoreP1HarnessTasksRouteWithChildren
  ApiCoreP1WorkflowsWorkflowIdEventsRoute: typeof ApiCoreP1WorkflowsWorkflowIdEventsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pwa-proof': {
      id: '/pwa-proof'
      path: '/pwa-proof'
      fullPath: '/pwa-proof'
      preLoaderRoute: typeof PwaProofRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototype-marketing-home': {
      id: '/prototype-marketing-home'
      path: '/prototype-marketing-home'
      fullPath: '/prototype-marketing-home'
      preLoaderRoute: typeof PrototypeMarketingHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro-studio': {
      id: '/pro-studio'
      path: '/pro-studio'
      fullPath: '/pro-studio'
      preLoaderRoute: typeof ProStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifest.json': {
      id: '/manifest.json'
      path: '/manifest.json'
      fullPath: '/manifest.json'
      preLoaderRoute: typeof ManifestDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heroui-spike': {
      id: '/heroui-spike'
      path: '/heroui-spike'
      fullPath: '/heroui-spike'
      preLoaderRoute: typeof HerouiSpikeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/heroui-spike/': {
      id: '/heroui-spike/'
      path: '/'
      fullPath: '/heroui-spike/'
      preLoaderRoute: typeof HerouiSpikeIndexRouteImport
      parentRoute: typeof HerouiSpikeRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/settings/security': {
      id: '/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSecurityRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/payment': {
      id: '/settings/payment'
      path: '/payment'
      fullPath: '/settings/payment'
      preLoaderRoute: typeof SettingsPaymentRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/models': {
      id: '/settings/models'
      path: '/models'
      fullPath: '/settings/models'
      preLoaderRoute: typeof SettingsModelsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/integrations': {
      id: '/settings/integrations'
      path: '/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof SettingsIntegrationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/files': {
      id: '/settings/files'
      path: '/files'
      fullPath: '/settings/files'
      preLoaderRoute: typeof SettingsFilesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/credits': {
      id: '/settings/credits'
      path: '/credits'
      fullPath: '/settings/credits'
      preLoaderRoute: typeof SettingsCreditsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/connections': {
      id: '/settings/connections'
      path: '/connections'
      fullPath: '/settings/connections'
      preLoaderRoute: typeof SettingsConnectionsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/billing': {
      id: '/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof SettingsBillingRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/apikeys': {
      id: '/settings/apikeys'
      path: '/apikeys'
      fullPath: '/settings/apikeys'
      preLoaderRoute: typeof SettingsApikeysRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/account': {
      id: '/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof SettingsAccountRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/heroui-spike/dashboard': {
      id: '/heroui-spike/dashboard'
      path: '/dashboard'
      fullPath: '/heroui-spike/dashboard'
      preLoaderRoute: typeof HerouiSpikeDashboardRouteImport
      parentRoute: typeof HerouiSpikeRoute
    }
    '/heroui-spike/chat': {
      id: '/heroui-spike/chat'
      path: '/chat'
      fullPath: '/heroui-spike/chat'
      preLoaderRoute: typeof HerouiSpikeChatRouteImport
      parentRoute: typeof HerouiSpikeRoute
    }
    '/dashboard/works': {
      id: '/dashboard/works'
      path: '/works'
      fullPath: '/dashboard/works'
      preLoaderRoute: typeof DashboardWorksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tasks': {
      id: '/dashboard/tasks'
      path: '/tasks'
      fullPath: '/dashboard/tasks'
      preLoaderRoute: typeof DashboardTasksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/store': {
      id: '/dashboard/store'
      path: '/store'
      fullPath: '/dashboard/store'
      preLoaderRoute: typeof DashboardStoreRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/sessions': {
      id: '/dashboard/sessions'
      path: '/sessions'
      fullPath: '/dashboard/sessions'
      preLoaderRoute: typeof DashboardSessionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/search': {
      id: '/dashboard/search'
      path: '/search'
      fullPath: '/dashboard/search'
      preLoaderRoute: typeof DashboardSearchRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/recent': {
      id: '/dashboard/recent'
      path: '/recent'
      fullPath: '/dashboard/recent'
      preLoaderRoute: typeof DashboardRecentRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/leads': {
      id: '/dashboard/leads'
      path: '/leads'
      fullPath: '/dashboard/leads'
      preLoaderRoute: typeof DashboardLeadsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/jobs': {
      id: '/dashboard/jobs'
      path: '/jobs'
      fullPath: '/dashboard/jobs'
      preLoaderRoute: typeof DashboardJobsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/content': {
      id: '/dashboard/content'
      path: '/content'
      fullPath: '/dashboard/content'
      preLoaderRoute: typeof DashboardContentRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/catalog': {
      id: '/dashboard/catalog'
      path: '/catalog'
      fullPath: '/dashboard/catalog'
      preLoaderRoute: typeof DashboardCatalogRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/assets': {
      id: '/dashboard/assets'
      path: '/assets'
      fullPath: '/dashboard/assets'
      preLoaderRoute: typeof DashboardAssetsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/error': {
      id: '/auth/error'
      path: '/error'
      fullPath: '/auth/error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/ping': {
      id: '/api/ping'
      path: '/api/ping'
      fullPath: '/api/ping'
      preLoaderRoute: typeof ApiPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/templates': {
      id: '/admin/templates'
      path: '/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AdminTemplatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/supply': {
      id: '/admin/supply'
      path: '/supply'
      fullPath: '/admin/supply'
      preLoaderRoute: typeof AdminSupplyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/redemptions': {
      id: '/admin/redemptions'
      path: '/redemptions'
      fullPath: '/admin/redemptions'
      preLoaderRoute: typeof AdminRedemptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plans': {
      id: '/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AdminPlansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/p1': {
      id: '/admin/p1'
      path: '/p1'
      fullPath: '/admin/p1'
      preLoaderRoute: typeof AdminP1RouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/models': {
      id: '/admin/models'
      path: '/models'
      fullPath: '/admin/models'
      preLoaderRoute: typeof AdminModelsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/integrations': {
      id: '/admin/integrations'
      path: '/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AdminIntegrationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cloudflare': {
      id: '/admin/cloudflare'
      path: '/cloudflare'
      fullPath: '/admin/cloudflare'
      preLoaderRoute: typeof AdminCloudflareRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/capabilities': {
      id: '/admin/capabilities'
      path: '/capabilities'
      fullPath: '/admin/capabilities'
      preLoaderRoute: typeof AdminCapabilitiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/(tests)/test-error': {
      id: '/(tests)/test-error'
      path: '/test-error'
      fullPath: '/test-error'
      preLoaderRoute: typeof testsTestErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(tests)/test-404': {
      id: '/(tests)/test-404'
      path: '/test-404'
      fullPath: '/test-404'
      preLoaderRoute: typeof testsTest404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)/pricing': {
      id: '/(pages)/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof pagesPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)/contact': {
      id: '/(pages)/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof pagesContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(legals)/terms': {
      id: '/(legals)/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof legalsTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(legals)/privacy': {
      id: '/(legals)/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof legalsPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(legals)/cookie': {
      id: '/(legals)/cookie'
      path: '/cookie'
      fullPath: '/cookie'
      preLoaderRoute: typeof legalsCookieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/works_/$workId': {
      id: '/dashboard/works_/$workId'
      path: '/works/$workId'
      fullPath: '/dashboard/works/$workId'
      preLoaderRoute: typeof DashboardWorksWorkIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tools_/$toolEntryId': {
      id: '/dashboard/tools_/$toolEntryId'
      path: '/tools/$toolEntryId'
      fullPath: '/dashboard/tools/$toolEntryId'
      preLoaderRoute: typeof DashboardToolsToolEntryIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tasks_/$taskId': {
      id: '/dashboard/tasks_/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/dashboard/tasks/$taskId'
      preLoaderRoute: typeof DashboardTasksTaskIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/sessions_/$sessionId': {
      id: '/dashboard/sessions_/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/dashboard/sessions/$sessionId'
      preLoaderRoute: typeof DashboardSessionsSessionIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/results_/$workId': {
      id: '/dashboard/results_/$workId'
      path: '/results/$workId'
      fullPath: '/dashboard/results/$workId'
      preLoaderRoute: typeof DashboardResultsWorkIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/leads_/$leadId': {
      id: '/dashboard/leads_/$leadId'
      path: '/leads/$leadId'
      fullPath: '/dashboard/leads/$leadId'
      preLoaderRoute: typeof DashboardLeadsLeadIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/jobs_/$jobId': {
      id: '/dashboard/jobs_/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/dashboard/jobs/$jobId'
      preLoaderRoute: typeof DashboardJobsJobIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/handoff/$token': {
      id: '/dashboard/handoff/$token'
      path: '/handoff/$token'
      fullPath: '/dashboard/handoff/$token'
      preLoaderRoute: typeof DashboardHandoffTokenRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/content_/$contentId': {
      id: '/dashboard/content_/$contentId'
      path: '/content/$contentId'
      fullPath: '/dashboard/content/$contentId'
      preLoaderRoute: typeof DashboardContentContentIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/assets_/$assetId': {
      id: '/dashboard/assets_/$assetId'
      path: '/assets/$assetId'
      fullPath: '/dashboard/assets/$assetId'
      preLoaderRoute: typeof DashboardAssetsAssetIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/webhooks/stripe': {
      id: '/api/webhooks/stripe'
      path: '/api/webhooks/stripe'
      fullPath: '/api/webhooks/stripe'
      preLoaderRoute: typeof ApiWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/creem': {
      id: '/api/webhooks/creem'
      path: '/api/webhooks/creem'
      fullPath: '/api/webhooks/creem'
      preLoaderRoute: typeof ApiWebhooksCreemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/upload': {
      id: '/api/storage/upload'
      path: '/api/storage/upload'
      fullPath: '/api/storage/upload'
      preLoaderRoute: typeof ApiStorageUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/file': {
      id: '/api/storage/file'
      path: '/api/storage/file'
      fullPath: '/api/storage/file'
      preLoaderRoute: typeof ApiStorageFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pro-studio/launch': {
      id: '/api/pro-studio/launch'
      path: '/api/pro-studio/launch'
      fullPath: '/api/pro-studio/launch'
      preLoaderRoute: typeof ApiProStudioLaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pro-studio/entry': {
      id: '/api/pro-studio/entry'
      path: '/api/pro-studio/entry'
      fullPath: '/api/pro-studio/entry'
      preLoaderRoute: typeof ApiProStudioEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pro-studio/checkout': {
      id: '/api/pro-studio/checkout'
      path: '/api/pro-studio/checkout'
      fullPath: '/api/pro-studio/checkout'
      preLoaderRoute: typeof ApiProStudioCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/e2e/users': {
      id: '/api/e2e/users'
      path: '/api/e2e/users'
      fullPath: '/api/e2e/users'
      preLoaderRoute: typeof ApiE2eUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/e2e/pro-studio-payment': {
      id: '/api/e2e/pro-studio-payment'
      path: '/api/e2e/pro-studio-payment'
      fullPath: '/api/e2e/pro-studio-payment'
      preLoaderRoute: typeof ApiE2eProStudioPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/core/diagnostics': {
      id: '/api/core/diagnostics'
      path: '/api/core/diagnostics'
      fullPath: '/api/core/diagnostics'
      preLoaderRoute: typeof ApiCoreDiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/core/product/state': {
      id: '/api/core/product/state'
      path: '/api/core/product/state'
      fullPath: '/api/core/product/state'
      preLoaderRoute: typeof ApiCoreProductStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/core/product/commands': {
      id: '/api/core/product/commands'
      path: '/api/core/product/commands'
      fullPath: '/api/core/product/commands'
      preLoaderRoute: typeof ApiCoreProductCommandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/core/p1/query': {
      id: '/api/core/p1/query'
      path: '/api/core/p1/query'
      fullPath: '/api/core/p1/query'
      preLoaderRoute: typeof ApiCoreP1QueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/core/p1/pending-actions': {
      id: '/api/core/p1/pending-actions'
      path: '/api/core/p1/pending-actions'
      fullPath: '/api/core/p1/pending-actions'
      preLoaderRoute: typeof ApiCoreP1PendingActionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/core/p1/commands': {
      id: '/api/core/p1/commands'
      path: '/api/core/p1/commands'
      fullPath: '/api/core/p1/commands'
      preLoaderRoute: typeof ApiCoreP1CommandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/core/p1/assets': {
      id: '/api/core/p1/assets'
      path: '/api/core/p1/assets'
      fullPath: '/api/core/p1/assets'
      preLoaderRoute: typeof ApiCoreP1AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/supply/views/$viewId': {
      id: '/admin/supply/views/$viewId'
      path: '/views/$viewId'
      fullPath: '/admin/supply/views/$viewId'
      preLoaderRoute: typeof AdminSupplyViewsViewIdRouteImport
      parentRoute: typeof AdminSupplyRoute
    }
    '/admin/supply/tasks/$taskId': {
      id: '/admin/supply/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/admin/supply/tasks/$taskId'
      preLoaderRoute: typeof AdminSupplyTasksTaskIdRouteImport
      parentRoute: typeof AdminSupplyRoute
    }
    '/api/core/p1/harness/tasks': {
      id: '/api/core/p1/harness/tasks'
      path: '/api/core/p1/harness/tasks'
      fullPath: '/api/core/p1/harness/tasks'
      preLoaderRoute: typeof ApiCoreP1HarnessTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/core/p1/harness/recommendation': {
      id: '/api/core/p1/harness/recommendation'
      path: '/api/core/p1/harness/recommendation'
      fullPath: '/api/core/p1/harness/recommendation'
      preLoaderRoute: typeof ApiCoreP1HarnessRecommendationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/core/p1/copy/stream': {
      id: '/api/core/p1/copy/stream'
      path: '/api/core/p1/copy/stream'
      fullPath: '/api/core/p1/copy/stream'
      preLoaderRoute: typeof ApiCoreP1CopyStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/core/p1/composer/submissions': {
      id: '/api/core/p1/composer/submissions'
      path: '/api/core/p1/composer/submissions'
      fullPath: '/api/core/p1/composer/submissions'
      preLoaderRoute: typeof ApiCoreP1ComposerSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/core/p1/assistant/stream': {
      id: '/api/core/p1/assistant/stream'
      path: '/api/core/p1/assistant/stream'
      fullPath: '/api/core/p1/assistant/stream'
      preLoaderRoute: typeof ApiCoreP1AssistantStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/core/diagnostics/$id/resume': {
      id: '/api/core/diagnostics/$id/resume'
      path: '/$id/resume'
      fullPath: '/api/core/diagnostics/$id/resume'
      preLoaderRoute: typeof ApiCoreDiagnosticsIdResumeRouteImport
      parentRoute: typeof ApiCoreDiagnosticsRoute
    }
    '/api/core/diagnostics/$id/events': {
      id: '/api/core/diagnostics/$id/events'
      path: '/$id/events'
      fullPath: '/api/core/diagnostics/$id/events'
      preLoaderRoute: typeof ApiCoreDiagnosticsIdEventsRouteImport
      parentRoute: typeof ApiCoreDiagnosticsRoute
    }
    '/api/core/p1/workflows/$workflowId/events': {
      id: '/api/core/p1/workflows/$workflowId/events'
      path: '/api/core/p1/workflows/$workflowId/events'
      fullPath: '/api/core/p1/workflows/$workflowId/events'
      preLoaderRoute: typeof ApiCoreP1WorkflowsWorkflowIdEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/core/p1/harness/tasks/$taskId/product-metrics': {
      id: '/api/core/p1/harness/tasks/$taskId/product-metrics'
      path: '/$taskId/product-metrics'
      fullPath: '/api/core/p1/harness/tasks/$taskId/product-metrics'
      preLoaderRoute: typeof ApiCoreP1HarnessTasksTaskIdProductMetricsRouteImport
      parentRoute: typeof ApiCoreP1HarnessTasksRoute
    }
    '/api/core/p1/harness/tasks/$taskId/decision': {
      id: '/api/core/p1/harness/tasks/$taskId/decision'
      path: '/$taskId/decision'
      fullPath: '/api/core/p1/harness/tasks/$taskId/decision'
      preLoaderRoute: typeof ApiCoreP1HarnessTasksTaskIdDecisionRouteImport
      parentRoute: typeof ApiCoreP1HarnessTasksRoute
    }
  }
}

interface AdminSupplyRouteChildren {
  AdminSupplyTasksTaskIdRoute: typeof AdminSupplyTasksTaskIdRoute
  AdminSupplyViewsViewIdRoute: typeof AdminSupplyViewsViewIdRoute
}

const AdminSupplyRouteChildren: AdminSupplyRouteChildren = {
  AdminSupplyTasksTaskIdRoute: AdminSupplyTasksTaskIdRoute,
  AdminSupplyViewsViewIdRoute: AdminSupplyViewsViewIdRoute,
}

const AdminSupplyRouteWithChildren = AdminSupplyRoute._addFileChildren(
  AdminSupplyRouteChildren,
)

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCapabilitiesRoute: typeof AdminCapabilitiesRoute
  AdminCloudflareRoute: typeof AdminCloudflareRoute
  AdminIntegrationsRoute: typeof AdminIntegrationsRoute
  AdminModelsRoute: typeof AdminModelsRoute
  AdminP1Route: typeof AdminP1Route
  AdminPlansRoute: typeof AdminPlansRoute
  AdminRedemptionsRoute: typeof AdminRedemptionsRoute
  AdminSupplyRoute: typeof AdminSupplyRouteWithChildren
  AdminTemplatesRoute: typeof AdminTemplatesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminCapabilitiesRoute: AdminCapabilitiesRoute,
  AdminCloudflareRoute: AdminCloudflareRoute,
  AdminIntegrationsRoute: AdminIntegrationsRoute,
  AdminModelsRoute: AdminModelsRoute,
  AdminP1Route: AdminP1Route,
  AdminPlansRoute: AdminPlansRoute,
  AdminRedemptionsRoute: AdminRedemptionsRoute,
  AdminSupplyRoute: AdminSupplyRouteWithChildren,
  AdminTemplatesRoute: AdminTemplatesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthErrorRoute: typeof AuthErrorRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthErrorRoute: AuthErrorRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardRouteChildren {
  DashboardAssetsRoute: typeof DashboardAssetsRoute
  DashboardCatalogRoute: typeof DashboardCatalogRoute
  DashboardContentRoute: typeof DashboardContentRoute
  DashboardJobsRoute: typeof DashboardJobsRoute
  DashboardLeadsRoute: typeof DashboardLeadsRoute
  DashboardRecentRoute: typeof DashboardRecentRoute
  DashboardSearchRoute: typeof DashboardSearchRoute
  DashboardSessionsRoute: typeof DashboardSessionsRoute
  DashboardStoreRoute: typeof DashboardStoreRoute
  DashboardTasksRoute: typeof DashboardTasksRoute
  DashboardWorksRoute: typeof DashboardWorksRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAssetsAssetIdRoute: typeof DashboardAssetsAssetIdRoute
  DashboardContentContentIdRoute: typeof DashboardContentContentIdRoute
  DashboardHandoffTokenRoute: typeof DashboardHandoffTokenRoute
  DashboardJobsJobIdRoute: typeof DashboardJobsJobIdRoute
  DashboardLeadsLeadIdRoute: typeof DashboardLeadsLeadIdRoute
  DashboardResultsWorkIdRoute: typeof DashboardResultsWorkIdRoute
  DashboardSessionsSessionIdRoute: typeof DashboardSessionsSessionIdRoute
  DashboardTasksTaskIdRoute: typeof DashboardTasksTaskIdRoute
  DashboardToolsToolEntryIdRoute: typeof DashboardToolsToolEntryIdRoute
  DashboardWorksWorkIdRoute: typeof DashboardWorksWorkIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAssetsRoute: DashboardAssetsRoute,
  DashboardCatalogRoute: DashboardCatalogRoute,
  DashboardContentRoute: DashboardContentRoute,
  DashboardJobsRoute: DashboardJobsRoute,
  DashboardLeadsRoute: DashboardLeadsRoute,
  DashboardRecentRoute: DashboardRecentRoute,
  DashboardSearchRoute: DashboardSearchRoute,
  DashboardSessionsRoute: DashboardSessionsRoute,
  DashboardStoreRoute: DashboardStoreRoute,
  DashboardTasksRoute: DashboardTasksRoute,
  DashboardWorksRoute: DashboardWorksRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAssetsAssetIdRoute: DashboardAssetsAssetIdRoute,
  DashboardContentContentIdRoute: DashboardContentContentIdRoute,
  DashboardHandoffTokenRoute: DashboardHandoffTokenRoute,
  DashboardJobsJobIdRoute: DashboardJobsJobIdRoute,
  DashboardLeadsLeadIdRoute: DashboardLeadsLeadIdRoute,
  DashboardResultsWorkIdRoute: DashboardResultsWorkIdRoute,
  DashboardSessionsSessionIdRoute: DashboardSessionsSessionIdRoute,
  DashboardTasksTaskIdRoute: DashboardTasksTaskIdRoute,
  DashboardToolsToolEntryIdRoute: DashboardToolsToolEntryIdRoute,
  DashboardWorksWorkIdRoute: DashboardWorksWorkIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface HerouiSpikeRouteChildren {
  HerouiSpikeChatRoute: typeof HerouiSpikeChatRoute
  HerouiSpikeDashboardRoute: typeof HerouiSpikeDashboardRoute
  HerouiSpikeIndexRoute: typeof HerouiSpikeIndexRoute
}

const HerouiSpikeRouteChildren: HerouiSpikeRouteChildren = {
  HerouiSpikeChatRoute: HerouiSpikeChatRoute,
  HerouiSpikeDashboardRoute: HerouiSpikeDashboardRoute,
  HerouiSpikeIndexRoute: HerouiSpikeIndexRoute,
}

const HerouiSpikeRouteWithChildren = HerouiSpikeRoute._addFileChildren(
  HerouiSpikeRouteChildren,
)

interface SettingsRouteChildren {
  SettingsAccountRoute: typeof SettingsAccountRoute
  SettingsApikeysRoute: typeof SettingsApikeysRoute
  SettingsBillingRoute: typeof SettingsBillingRoute
  SettingsConnectionsRoute: typeof SettingsConnectionsRoute
  SettingsCreditsRoute: typeof SettingsCreditsRoute
  SettingsFilesRoute: typeof SettingsFilesRoute
  SettingsIntegrationsRoute: typeof SettingsIntegrationsRoute
  SettingsModelsRoute: typeof SettingsModelsRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsPaymentRoute: typeof SettingsPaymentRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsSecurityRoute: typeof SettingsSecurityRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAccountRoute: SettingsAccountRoute,
  SettingsApikeysRoute: SettingsApikeysRoute,
  SettingsBillingRoute: SettingsBillingRoute,
  SettingsConnectionsRoute: SettingsConnectionsRoute,
  SettingsCreditsRoute: SettingsCreditsRoute,
  SettingsFilesRoute: SettingsFilesRoute,
  SettingsIntegrationsRoute: SettingsIntegrationsRoute,
  SettingsModelsRoute: SettingsModelsRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsPaymentRoute: SettingsPaymentRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsSecurityRoute: SettingsSecurityRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface ApiCoreDiagnosticsRouteChildren {
  ApiCoreDiagnosticsIdEventsRoute: typeof ApiCoreDiagnosticsIdEventsRoute
  ApiCoreDiagnosticsIdResumeRoute: typeof ApiCoreDiagnosticsIdResumeRoute
}

const ApiCoreDiagnosticsRouteChildren: ApiCoreDiagnosticsRouteChildren = {
  ApiCoreDiagnosticsIdEventsRoute: ApiCoreDiagnosticsIdEventsRoute,
  ApiCoreDiagnosticsIdResumeRoute: ApiCoreDiagnosticsIdResumeRoute,
}

const ApiCoreDiagnosticsRouteWithChildren =
  ApiCoreDiagnosticsRoute._addFileChildren(ApiCoreDiagnosticsRouteChildren)

interface ApiCoreP1HarnessTasksRouteChildren {
  ApiCoreP1HarnessTasksTaskIdDecisionRoute: typeof ApiCoreP1HarnessTasksTaskIdDecisionRoute
  ApiCoreP1HarnessTasksTaskIdProductMetricsRoute: typeof ApiCoreP1HarnessTasksTaskIdProductMetricsRoute
}

const ApiCoreP1HarnessTasksRouteChildren: ApiCoreP1HarnessTasksRouteChildren = {
  ApiCoreP1HarnessTasksTaskIdDecisionRoute:
    ApiCoreP1HarnessTasksTaskIdDecisionRoute,
  ApiCoreP1HarnessTasksTaskIdProductMetricsRoute:
    ApiCoreP1HarnessTasksTaskIdProductMetricsRoute,
}

const ApiCoreP1HarnessTasksRouteWithChildren =
  ApiCoreP1HarnessTasksRoute._addFileChildren(
    ApiCoreP1HarnessTasksRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  HerouiSpikeRoute: HerouiSpikeRouteWithChildren,
  ManifestDotjsonRoute: ManifestDotjsonRoute,
  ProStudioRoute: ProStudioRoute,
  PrototypeMarketingHomeRoute: PrototypeMarketingHomeRoute,
  PwaProofRoute: PwaProofRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  legalsCookieRoute: legalsCookieRoute,
  legalsPrivacyRoute: legalsPrivacyRoute,
  legalsTermsRoute: legalsTermsRoute,
  pagesContactRoute: pagesContactRoute,
  pagesPricingRoute: pagesPricingRoute,
  testsTest404Route: testsTest404Route,
  testsTestErrorRoute: testsTestErrorRoute,
  ApiPingRoute: ApiPingRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCoreDiagnosticsRoute: ApiCoreDiagnosticsRouteWithChildren,
  ApiE2eProStudioPaymentRoute: ApiE2eProStudioPaymentRoute,
  ApiE2eUsersRoute: ApiE2eUsersRoute,
  ApiProStudioCheckoutRoute: ApiProStudioCheckoutRoute,
  ApiProStudioEntryRoute: ApiProStudioEntryRoute,
  ApiProStudioLaunchRoute: ApiProStudioLaunchRoute,
  ApiStorageFileRoute: ApiStorageFileRoute,
  ApiStorageUploadRoute: ApiStorageUploadRoute,
  ApiWebhooksCreemRoute: ApiWebhooksCreemRoute,
  ApiWebhooksStripeRoute: ApiWebhooksStripeRoute,
  ApiCoreP1AssetsRoute: ApiCoreP1AssetsRoute,
  ApiCoreP1CommandsRoute: ApiCoreP1CommandsRoute,
  ApiCoreP1PendingActionsRoute: ApiCoreP1PendingActionsRoute,
  ApiCoreP1QueryRoute: ApiCoreP1QueryRoute,
  ApiCoreProductCommandsRoute: ApiCoreProductCommandsRoute,
  ApiCoreProductStateRoute: ApiCoreProductStateRoute,
  ApiCoreP1AssistantStreamRoute: ApiCoreP1AssistantStreamRoute,
  ApiCoreP1ComposerSubmissionsRoute: ApiCoreP1ComposerSubmissionsRoute,
  ApiCoreP1CopyStreamRoute: ApiCoreP1CopyStreamRoute,
  ApiCoreP1HarnessRecommendationRoute: ApiCoreP1HarnessRecommendationRoute,
  ApiCoreP1HarnessTasksRoute: ApiCoreP1HarnessTasksRouteWithChildren,
  ApiCoreP1WorkflowsWorkflowIdEventsRoute:
    ApiCoreP1WorkflowsWorkflowIdEventsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
