/**
 * Versioned capability inventory (D-051 decision ③).
 * instrumented domains are deepened by J1+; stubs keep six-question minimum fields.
 * Audio = not_instrumented / not_in_scope_for_supply_v1 — must remain visible.
 */
import type { CapabilityInventoryDocument } from '@meiye/contracts';

export const CAPABILITY_INVENTORY_REVISION = 'cap-inventory-2026-07-20.v1';

export const CAPABILITY_INVENTORY: CapabilityInventoryDocument = {
  revision: CAPABILITY_INVENTORY_REVISION,
  capturedAt: '2026-07-20T00:00:00.000Z',
  items: [
    {
      id: 'account_auth',
      name: '账号与认证',
      purpose: '登录身份、会话与平台/工作区角色门',
      group: 'account_and_commerce',
      status: 'stub',
      owner: 'foundation/access-control',
      drilldownKey: 'admin.account',
      criticalDependencies: ['config_secrets'],
    },
    {
      id: 'entitlements_billing_redemption',
      name: '套餐权益支付兑换码',
      purpose: '套餐额度、并发与兑换发放',
      group: 'account_and_commerce',
      status: 'instrumented',
      owner: 'foundation/entitlements',
      drilldownKey: 'admin.entitlements',
      criticalDependencies: ['account_auth', 'observability_audit'],
    },
    {
      id: 'model_supply_routing_quality',
      name: '模型供应商与路由质量',
      purpose: '多渠道供应实体、路由策略、健康与质量门',
      group: 'ai_supply_and_generation',
      status: 'instrumented',
      owner: 'model-supply',
      drilldownKey: 'admin.supply',
      criticalDependencies: ['config_secrets', 'job_queue_harness', 'observability_audit'],
    },
    {
      id: 'generation_copy',
      name: '文案生成',
      purpose: '结构化文案与平台改写',
      group: 'ai_supply_and_generation',
      status: 'instrumented',
      owner: 'model-supply/copy',
      drilldownKey: 'admin.supply.copy',
      criticalDependencies: ['model_supply_routing_quality', 'entitlements_billing_redemption'],
    },
    {
      id: 'generation_image',
      name: '图片生成',
      purpose: '图片生成与编辑异步链路',
      group: 'ai_supply_and_generation',
      status: 'instrumented',
      owner: 'model-supply/image',
      drilldownKey: 'admin.supply.image',
      criticalDependencies: ['model_supply_routing_quality', 'data_storage'],
    },
    {
      id: 'generation_video',
      name: '视频生成',
      purpose: '视频工作流与成片交付',
      group: 'ai_supply_and_generation',
      status: 'instrumented',
      owner: 'model-supply/video',
      drilldownKey: 'admin.supply.video',
      criticalDependencies: ['model_supply_routing_quality', 'data_storage', 'job_queue_harness'],
    },
    {
      id: 'generation_audio',
      name: '音频生成',
      purpose: '语音/音效供应（首轮供应闭环不在 scope）',
      group: 'ai_supply_and_generation',
      status: 'not_in_scope_for_supply_v1',
      owner: 'model-supply/audio',
      drilldownKey: 'admin.supply.audio',
      criticalDependencies: ['model_supply_routing_quality'],
      notes: 'not_instrumented for supply v1; inventory stub retained per D-051/D-068',
    },
    {
      id: 'job_queue_harness',
      name: 'Harness 任务队列',
      purpose: '任务提交、并发门、恢复与运行指标',
      group: 'task_orchestration',
      status: 'instrumented',
      owner: 'job-runtime',
      drilldownKey: 'admin.jobs',
      criticalDependencies: ['observability_audit', 'data_storage'],
    },
    {
      id: 'content_package_canvas',
      name: 'ContentPackage 模板素材画布',
      purpose: '内容包、模板与画布资产',
      group: 'content_and_assets',
      status: 'stub',
      owner: 'operations/content-package',
      drilldownKey: 'admin.content',
      criticalDependencies: ['data_storage', 'generation_image'],
    },
    {
      id: 'channel_tool_integrations',
      name: '渠道与工具集成',
      purpose: '飞书/抖音等外部连接与发布移交',
      group: 'external_integrations',
      status: 'stub',
      owner: 'integrations',
      drilldownKey: 'admin.integrations',
      criticalDependencies: ['config_secrets', 'account_auth'],
    },
    {
      id: 'data_storage',
      name: '数据与存储',
      purpose: '业务库、对象资产与持久化边界',
      group: 'runtime_and_governance',
      status: 'stub',
      owner: 'foundation/persistence',
      drilldownKey: 'admin.storage',
      criticalDependencies: ['config_secrets'],
    },
    {
      id: 'config_secrets',
      name: '配置密钥',
      purpose: '配置 revision 与密钥引用（非明文）',
      group: 'runtime_and_governance',
      status: 'stub',
      owner: 'admin-config + secret-store',
      drilldownKey: 'admin.config',
      criticalDependencies: [],
    },
    {
      id: 'observability_audit',
      name: '观测告警审计',
      purpose: '运行指标、审计与技术移交证据',
      group: 'runtime_and_governance',
      status: 'stub',
      owner: 'job-runtime/operational-metrics',
      drilldownKey: 'admin.audit',
      criticalDependencies: ['data_storage'],
    },
  ],
};
