/**
 * V3.1 Agent-domain contracts (V31-01).
 *
 * Ten domains: thread / run / goal / plan / memory / event / execution-plan /
 * release / steering / outcome. Shapes follow
 * docs/design/0808规划/meiye-agent-v3.1-authoritative-plan-2026-08-08.md
 * §7–§10, §12.5, §13–§14.2, §21.2, §22.2, §23.3–§24, §26–§27, §29.
 *
 * Pure contract layer — no runtime, DB, or UI.
 *
 * Physical split lives under ./agent-domain/; this file is the compatibility
 * barrel so existing `from './agent-domain.js'` imports keep working.
 */

export {
  agentRevisionRefSchema,
  type AgentRevisionRef,
  agentEvidenceRefSchema,
  type AgentEvidenceRef,
} from './agent-domain/shared.js';
export {
  AGENT_THREAD_SCHEMA_VERSION,
  agentThreadStatusSchema,
  agentThreadSchema,
  type AgentThread,
} from './agent-domain/thread.js';
export {
  AGENT_RUN_SCHEMA_VERSION,
  agentRunTriggerSchema,
  agentRunStatusSchema,
  agentRunDurabilitySchema,
  agentRunExecutionLinkSchema,
  type AgentRunExecutionLink,
  agentRunSchema,
  type AgentRun,
} from './agent-domain/run.js';
export {
  MARKETING_GOAL_SCHEMA_VERSION,
  marketingGoalObjectiveSchema,
  type MarketingGoalObjective,
  marketingGoalPrioritySchema,
  type MarketingGoalPriority,
  marketingGoalStatusSchema,
  type MarketingGoalStatus,
  marketingGoalSchema,
  type MarketingGoal,
  MARKETING_GOAL_PROPOSAL_SCHEMA_VERSION,
  marketingGoalProposalKindSchema,
  marketingGoalCreateDraftSchema,
  type MarketingGoalCreateDraft,
  marketingGoalProposalSchema,
  type MarketingGoalProposal,
  marketingGoalProgressSchema,
  type MarketingGoalProgress,
} from './agent-domain/goal.js';
export {
  OPPORTUNITY_CANDIDATE_SCHEMA_VERSION,
  opportunityCandidateStatusSchema,
  type OpportunityCandidateStatus,
  opportunityCandidateSchema,
  type OpportunityCandidate,
  OPPORTUNITY_DECISION_SCHEMA_VERSION,
  opportunityDecisionKindSchema,
  opportunityDecisionSchema,
  type OpportunityDecision,
  PROACTIVE_SIGNAL_KINDS,
  type ProactiveSignalKind,
  proactiveSignalSchema,
  type ProactiveSignal,
} from './agent-domain/opportunity.js';
export {
  MARKETING_PLAN_REVISION_SCHEMA_VERSION,
  marketingPlanScopeSchema,
  planDeliverableCarrierSchema,
  planDeliverableSchema,
  type PlanDeliverable,
  intentDeclarationSchema,
  type IntentDeclaration,
  planMemoryContextSchema,
  type PlanMemoryContext,
  marketingPlanRevisionSchema,
  type MarketingPlanRevision,
  marketingPlanReadinessSchema,
  type MarketingPlanReadiness,
} from './agent-domain/plan.js';
export {
  AGENT_MEMORY_ENTRY_SCHEMA_VERSION,
  agentMemoryKindSchema,
  agentMemoryAuthoritySchema,
  agentMemoryStateSchema,
  agentMemoryScopeSchema,
  type AgentMemoryScope,
  agentMemoryEntrySchema,
  type AgentMemoryEntry,
  MEMORY_INJECTION_RECEIPT_SCHEMA_VERSION,
  memoryInjectionReceiptSchema,
  type MemoryInjectionReceipt,
} from './agent-domain/memory.js';
export {
  AGENT_SEMANTIC_EVENT_SCHEMA_VERSION,
  agentEventContextRoleSchema,
  AGENT_SEMANTIC_EVENT_TYPES,
  agentSemanticEventTypeSchema,
  agentSemanticEventSchema,
  type AgentSemanticEvent,
  agentSemanticEventWireSchema,
  type AgentSemanticEventWire,
  AGENT_EPHEMERAL_EVENT_SCHEMA_VERSION,
  agentEphemeralEventWireSchema,
  type AgentEphemeralEventWire,
  agentSemanticEventToWire,
  agentSemanticEventFromWire,
  compareStreamOffsetWire,
} from './agent-domain/event.js';
export {
  ARTIFACT_UPDATE_SCHEMA_VERSION,
  artifactTypeSchema,
  type ArtifactType,
  artifactStatusSchema,
  type ArtifactStatus,
  artifactMediaStageSchema,
  notePageStateSchema,
  type NotePageState,
  videoSceneStateSchema,
  type VideoSceneState,
  copyBlockStateSchema,
  type CopyBlockState,
  planSectionStateSchema,
  type PlanSectionState,
  publishItemStateSchema,
  type PublishItemState,
  noteArtifactFullSchema,
  videoArtifactFullSchema,
  copyArtifactFullSchema,
  planArtifactFullSchema,
  imageArtifactFullSchema,
  publishArtifactFullSchema,
  artifactFullBodySchema,
  type ArtifactFullBody,
  notePagePatchSchema,
  noteArtifactPatchSchema,
  videoScenePatchSchema,
  videoArtifactPatchSchema,
  copyArtifactPatchSchema,
  planArtifactPatchSchema,
  imageArtifactPatchSchema,
  publishArtifactPatchSchema,
  artifactPatchBodySchema,
  type ArtifactPatchBody,
  artifactUpdateSnapshotSchema,
  artifactUpdateDeltaSchema,
  artifactUpdateWireSchema,
  type ArtifactUpdateWire,
  type ArtifactVersionRecord,
  type ArtifactProjectionState,
  type ApplyArtifactUpdateFailureReason,
  type ApplyArtifactUpdateResult,
  applyArtifactUpdate,
  createEmptyArtifactProjection,
  artifactDuplicateObjectRate,
} from './agent-domain/artifact.js';
export {
  COMPILED_EXECUTION_PLAN_SCHEMA_VERSION,
  executionUnitSchema,
  type ExecutionUnit,
  compiledExecutionCapabilitiesSchema,
  type CompiledExecutionCapabilities,
  CURRENT_COMPILED_EXECUTION_CAPABILITIES,
  compiledExecutionPlanSchema,
  type CompiledExecutionPlan,
  currentExecutionPlanCapabilityViolation,
  EXECUTION_PLAN_SNAPSHOT_SCHEMA_VERSION,
  executionPlanApprovalBasisSchema,
  type ExecutionPlanApprovalBasis,
  executionPlanPackageBillingAllocationSchema,
  type ExecutionPlanPackageBillingAllocation,
  executionPlanPackageBillingSchema,
  type ExecutionPlanPackageBilling,
  EXECUTION_PLAN_SNAPSHOT_HASH_COVERAGE_FIELDS,
  EXECUTION_PLAN_SNAPSHOT_HASH_EXCLUDED_FIELDS,
  promptRevisionRefSchema,
  skillManifestRefSchema,
  capabilityRequirementSchema,
  executionPlanSnapshotSchema,
  type ExecutionPlanSnapshot,
  AGENT_EXECUTION_CONFIRMATION_REQUEST_SCHEMA_VERSION,
  CONFIRMATION_HOLD_MIN_SECONDS,
  CONFIRMATION_HOLD_MAX_SECONDS,
  confirmationApprovalScopeSchema,
  type ConfirmationApprovalScope,
  agentExecutionConfirmationRequestSchema,
  type AgentExecutionConfirmationRequest,
  PLAN_CONFIRMATION_DECISION_SCHEMA_VERSION,
  planConfirmationDecisionSchema,
  type PlanConfirmationDecision,
} from './agent-domain/execution-plan.js';
export {
  HARNESS_RELEASE_ARTIFACT_SCHEMA_VERSION,
  agentControlLimitsSchema,
  type AgentControlLimits,
  harnessMiddlewareBindingSchema,
  type HarnessMiddlewareBinding,
  harnessReleaseArtifactSchema,
  type HarnessReleaseArtifact,
  HARNESS_RELEASE_LIFECYCLE_SCHEMA_VERSION,
  harnessReleaseLifecycleStatusSchema,
  harnessReleaseLifecycleSchema,
  type HarnessReleaseLifecycle,
  HARNESS_RELEASE_ROLLOUT_SCHEMA_VERSION,
  harnessReleaseRolloutSchema,
  type HarnessReleaseRollout,
} from './agent-domain/release.js';
export {
  STEERING_COMMAND_SCHEMA_VERSION,
  steeringClassificationSchema,
  type SteeringClassification,
  steeringQueueModeSchema,
  steeringUnitProgressSchema,
  type SteeringUnitProgress,
  makeSteeringCommandSchema,
  type MakeSteeringCommand,
} from './agent-domain/steering.js';
export {
  OUTCOME_EVIDENCE_SCHEMA_VERSION,
  outcomeSignalSchema,
  type OutcomeSignal,
  OUTCOME_SELF_REPORT_CHIP_SIGNALS,
  type OutcomeSelfReportChipSignal,
  outcomeSourceSchema,
  type OutcomeSource,
  outcomeEvidenceLifecycleStatusSchema,
  type OutcomeEvidenceLifecycleStatus,
  outcomeEvidenceWriteActionSchema,
  type OutcomeEvidenceWriteAction,
  outcomeEvidenceSchema,
  type OutcomeEvidence,
  buildOutcomeEvidenceIdempotencyKey,
  isForbiddenNoActivityEncoding,
  mapContentPackageResultKindToOutcomeSignal,
  mapOutcomeSignalToContentPackageResultKind,
  mapContentPackageResultSourceToOutcomeSource,
  mapOutcomeSourceToContentPackageResultSource,
  projectLatestOutcomeEvidence,
  OUTCOME_SELF_REPORT_FREQUENCY_PARAMS,
  outcomeSelfReportFrequencyParamsSchema,
  type OutcomeSelfReportFrequencyParams,
  recordOutcomeEvidenceCommandSchema,
  type RecordOutcomeEvidenceCommand,
} from './agent-domain/outcome.js';
export {
  INTERRUPT_PAYLOAD_SCHEMA_VERSION,
  interruptActionSchema,
  type InterruptAction,
  interruptConfigSchema,
  type InterruptConfig,
  interruptPayloadSchema,
  type InterruptPayload,
  resumeInterruptTypeSchema,
  type ResumeInterruptType,
  resumeInterruptCommandSchema,
  type ResumeInterruptCommand,
  listPendingInterruptsQuerySchema,
  type ListPendingInterruptsQuery,
  type WorkbenchSessionProjection,
  type WorkbenchSessionTaskRef,
} from './agent-domain/interrupt.js';
