export {
  assessImageExactText,
  candidateBillingDisposition,
  copySelectionCurrentBestSchema,
  executeImageSelection,
  executePlatformCopySelection,
  HarnessSelectionError,
  isCopySelectionCurrentBest,
  isNonSelfCorrectableSelectionError,
  type CopySelectionCurrentBest,
  type CopySelectionInput,
  type DecisionTraceFragment,
  type ImageExactTextAssessment,
  type ImageExactTextObservation,
} from './execution-selection-internal.js';
