export const CORE_SERVICE_NAME = 'meiye-core';
export { createCoreServer } from './server.js';
export type { DiagnosticRepository } from './diagnostics/repository.js';
export { PostgresDiagnosticRepository } from './diagnostics/postgres-repository.js';
export { PostgresProductRepository } from './product/postgres-repository.js';
export { DomainError, ProductService } from './product/product-service.js';
export { MemoryProductRepository } from './product/repository.js';
export type { ProductRepository } from './product/repository.js';
export * from './product/notifier.js';
export * from './product/quality-sink.js';
export * from './product/plans.js';
export * from './product/model-supply-copy-provider.js';
export * from './product/copy-prompt-library.js';
export * as P1Foundation from './p1/foundation/index.js';
export * as P1Cutover from './p1/cutover/index.js';
export * as P1Integrations from './p1/integrations/index.js';
export * as P1JobRuntime from './p1/job-runtime/index.js';
export * as P1ModelSupply from './p1/model-supply/index.js';
export * as P1Operations from './p1/operations/index.js';
export * as RuntimeTruth from './runtime-truth/index.js';
